### ISSUE TITLE
Question about CyberArk API

### ISSUE THREAD

**Issue by Sumu-Ning** [pspete/PoShPACLI#10]
Hi Pete,

I just found your project about the CyberArk API, it seems very powerful and exposed a lot to external to use.

In your case, you are using their command line API I guess, I am wondering whether you have information about their other API's? I read some information on their website, but cannot find more details.

Here is what is from them:
Vault Software Development Kit (SDK)
The CyberArk Vault SDK provides an interface to Vault objects and can be used to develop custom
solutions that work with the Vault. CyberArk provides a variety of SDKs such as Command Line
Interface, .Net API, Web Services API and REST API.
http://lp.cyberark.com/rs/cyberarksoftware/images/SB-Sensitive%20Information%20Management_Aug%202014-en.pdf

**Comment by pspete** [comment]
Hi,

You do get some documentation along with the APIs... I'm not able to share it here however.
As far as I am aware - all future development from CyberArk will be for the APIs and not the PACLI utility.

**Comment by Sumu-Ning** [comment]
Thank you for your quick response, and I do understand that you cannot share it.

However, if allowed, could you help checking whether the API is providing the same level of functionalities as the command line?

Thank you!

**Comment by pspete** [comment]
Sure.
I will confirm, but the last time I checked it was not yet as fully featured. Conversations I've had with CyberArk suggest the API route is the replacement for PACLI, so you'd expect the same functionality to appear eventually.
A PowerShell module for the REST API is on my TODO list ;-)

**Comment by Sumu-Ning** [comment]
Thank you for your help!

**Comment by pspete** [comment]
OK - having checked the documentation for the .NET API shipped with version 9.3, you can probably do everything that PACLI can do, and much much more. At a high level, there are "Data-related objects", "Find objects", "Administrative Operations" & "Catergories Operations" exposed through the API, far too many for me to copy from a CHM file to list here.

Hope this helps.
