### ISSUE TITLE
Update-User (UPDATEUSER) Question on Functionality

### ISSUE THREAD

**Issue by ghost** [pspete/PoShPACLI#12]
pspete - 

This is a question, I'm sorry if this is not the right place to inquire but I can't find a way to contact you directly. I have been trying to use PACLI script at my organization and I am having difficulty with the UPDATEUSER function. This is exactly what brought me to your script.

I have a requirement to be able to mass-update users in CyberArk and one request is requiring me to update the user's DN field. No matter how I've tried whether it be completely manually using pacli.exe and their structures or using your script, I cannot get this entered. I continually get parse errors. 

Example:

pacli UPDATEUSER VAULT="Vault" USER="user" DESTUSER="destuser" AUTHTYPE="LDAP_AUTH" DN="CN=Last\, First,OU=Users TEST,OU=ADC,OU=NOA,DC=test,DC=com"
**parse error, expecting `__PACLI_ENUM'**

Have you ever tested UPDATE-USER on your script with DN? I get similar parse errors under your script as well. This is, of course, after INIT and other required commands.

Thank you.

**Comment by pspete** [comment]
__PACLI_ENUM error on Update-User resolved via #18
