### ISSUE TITLE
Enable-TrustedNetworkArea/Disable-TrustedNetworkArea Functions

### ISSUE THREAD

**Issue by kevinelwell** [pspete/PoShPACLI#13]
First of all, thank you for making this awesome module and sharing it. The Enable-TrustedNetworkArea function and the Disable-TrustedNetworkArea function do not seem to work correctly. I am unable to make them work. I keep getting parse errors.  I manually deactivated my "username" account. I can see it is not active from the Get-TrustedNetworkArea -vault "$VaultName" -user "$LogonUser" -trusterName "$networkID" -Verbose function.

VERBOSE: Starting Pacli
VERBOSE: Pacli Started
True
VERBOSE: Defining Vault
VERBOSE: Vault Config Read
True
VERBOSE: Logging onto Vault
VERBOSE: Succesfully Logged on
True

Name              : All
FromHour          : 0
ToHour            : 24
Active            : NO
MaxViolationCount : 5
ViolationCount    : 0

Using the -Debug argument, I can see the command is getting the values with "" around them. 

DEBUG: Processing Bound Parameters
DEBUG: vault="VAULT" user="dude" trusterName="username" networkArea="All"
PACLI.EXE : parse error, expecting `__PACLI_STRING'At line:1 char:1
+ C:\Temp\v1.3\PACLI\PA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (parse error, expecting `__PACLI_STRING':String) [] 
   , RemoteException
    + FullyQualifiedErrorId : NativeCommandError

I referenced How to use parameters  issue #8, and tried changing line 5317 from $enableTrustedNetworkArea = Invoke-Expression "$pacli ACTIVATETRUSTEDNETWORKAREA $($PSBoundParameters.getEnumerator() | ConvertTo-ParameterString)" to $enableTrustedNetworkArea = Invoke-Expression "$pacli ACTIVATETRUSTEDNETWORKAREA $($PSBoundParameters.getEnumerator() | ConvertTo-ParameterString -quoteOutput)" without any luck. 

Any ideas?

**Comment by pspete** [comment]
Issues with Enable-TrustedNetworkArea & Disable-TrustedNetworkArea resolved via #18
