### ISSUE TITLE
Add-Safe issue

### ISSUE THREAD

**Issue by juler69** [pspete/PoShPACLI#14]
Hi Pete,

Thanks for a great tool!

I have a couple of bugs/enhancements I think...

When I use -Debug some of the functions fail because they are trying to write info using a non-existent array index.

For example:
`write-Debug $($addSafe[0]|Out-String)`

I altered the assignment statement to fix this, thus:
`[array]$addSafe = (Invoke-Expression...`

I did this on all the functions that write debug info in a similar fashion.

Also, when I use the Add-Safe function, if I include a description I get a PACLI error about a missing ';' 
I suspect this has something to do with the description having spaces in it.  I tried enclosing the description in quotes and terminating with an ';' and they both fail.

**Comment by juler69** [comment]
I fixed the issue where passing any value that has a space in it causes the command to fail with a parse error by replacing the Invoke-Expression with this:

```
        $ps = new-object System.Diagnostics.Process
        $ps.StartInfo.Filename = $pacli
        $ps.StartInfo.Arguments = " ADDOWNER $($PSBoundParameters.getEnumerator() | ConvertTo-ParameterString) "
        $ps.StartInfo.RedirectStandardOutput = $True
        $ps.StartInfo.UseShellExecute = $false
        $ps.start()
        $ps.WaitForExit()
        $safeOwner = $ps.StandardOutput.ReadToEnd();
```

This also addresses Issue #5

**Comment by pspete** [comment]
Hi @juler69 -

Thanks for contributing, I appreciate the input. 

Having not touched this project for nearly 2 years I am getting reaquainted with it and getting a lab configured to continue development of the module.

I will likely change the structure of the module to something similar to [psPAS](https://github.com/pspete/psPAS), with each function being a separate file, if only to make maintenance easier.

Your proposed fix sounds like a vast improvement on the initial commit....

**Comment by pspete** [comment]
Hi @juler69 - thanks for spurring me on to improve on the previous, neglected, incarnation of the module.
The debug output is different now - all thanks to replacing invoke-expression with a function based on the  code you supplied using new-object System.Diagnostics.Process...

**Comment by juler69** [comment]
No worries.  I will check it out.  Thanks for updating :D
