### ISSUE TITLE
Get-FilesList needs ability to allow subfolders

### ISSUE THREAD

**Issue by infamousjoeg** [pspete/PoShPACLI#21]
Trying to read policies in Root/Policies folder and I cannot get Get-FilesList to dive into subfolders.  Changing on my end.  If it works, will provide code.

**Comment by infamousjoeg** [comment]
I think I'm thinking of Search-Files... but I swear I thought Get-FilesList could do the same.

Either way, I can't get either of these functions to work.  @pspete did you have any issues when testing this?

**Comment by pspete** [comment]
I can't recall any issues @infamousjoeg - but I doubt I covered off all scenarios either.
Search-Files (FindFiles) does have a "includeSubFolders" parameter, but think this is Yes/True by default anyway.....

**Comment by pspete** [comment]
@infamousjoeg - issue resolved with Get-FilesList not returning results.... it still does not search subfolders, but the below will get the same result (until pipeline support arrives....):

- Get list of folders from open safe
`$folders = get-folder -vault abc-user 123 -safe Secret_Safe`

- loop through each folder on call to Get-FilesList
`$folders | select -expandproperty Name | %{Get-FilesList -vault abc -user 123 -safe Secret_Safe -folder $_}`
