### ISSUE TITLE
Test-ExePreReqs gives no indication of failure.

### ISSUE THREAD

**Issue by ghost** [pspete/PoShPACLI#22]
Commands like Connect-Vault depend on Test-ExePreReqs. If my prereqs fails, neither Test-ExePreReqs nor Connect-Vault generate any information stating I have a failure.

I can see either update Test-ExePreReqs with a Write-Warning stating something is missing from the PreReqs or updating Connect-Vault (and any other command that depends on it) to display a message stating something is missing.

**Comment by pspete** [comment]
Good shout @BrandonLundt - would be a definite enhancement.
I feel another module update brewing.....
