### ISSUE TITLE
Implement PSScriptAnalyzer Recommendations

### ISSUE THREAD

**Issue by ghost** [pspete/PoShPACLI#23]
These four functions fail with the following messages:

RuleName                                   | Severity    |ScriptName                       | Line |Message                                                                                                                   
--------                                   | --------    |----------                       | ----| -------                                                                                                                   
PSUseSupportsShouldProcess                 | Warning     |Confirm-Request.ps1              | 47  | Whatif and/or Confirm manually defined in function Confirm-Request. Instead, please use SupportsShouldProcess attribute.  
PSUseBOMForUnicodeEncodedFile              | Warning     |Confirm-Request.ps1              |     | Missing BOM encoding for non-ASCII encoded file 'Confirm-Request.ps1'                                                     
PSUseBOMForUnicodeEncodedFile              | Warning     |Get-RequestConfirmationStatus.ps1|     | Missing BOM encoding for non-ASCII encoded file 'Get-RequestConfirmationStatus.ps1'                                       
PSUseBOMForUnicodeEncodedFile              | Warning     |Get-RequestsList.ps1             |     | Missing BOM encoding for non-ASCII encoded file 'Get-RequestsList.ps1'                                                    
PSUseBOMForUnicodeEncodedFile              | Warning     |Remove-Request.ps1               |     | Missing BOM encoding for non-ASCII encoded file 'Remove-Request.ps1'                                                      
PSUseShouldProcessForStateChangingFunctions| Warning     |Remove-Request.ps1               | 1   | Function ’Remove-Request’ has verb that could change system state. Therefore, the function has to support 'ShouldProcess'.
PSUseOutputTypeCorrectly                   | Information |Remove-Request.ps1               | 62  | The cmdlet 'Remove-Request' returns an object of type 'System.Boolean' but this type is not declared in the OutputType attribute.
PSUseOutputTypeCorrectly                   | Information |Remove-Request.ps1               | 68 |  The cmdlet 'Remove-Request' returns an object of type 'System.Boolean' but this type is not declared in the OutputType attribute.  

Some of these correspond to the effort in issue #3

**Comment by pspete** [comment]
The PSUseBOMForUnicodeEncodedFile warnings should be fixed accross all files now.....

**Comment by ghost** [comment]
I have updated the files in the Requests folder, however when I go to submit a pull request, it shows that every file will be updated. I feel I have done something terribly wrong. 

Any advice?

**Comment by pspete** [comment]
You can compare the differences here:
https://github.com/BrandonLundt/PoShPACLI/compare/master...pspete:master

it looks like you do not have the latests updates to the master branch (I added examples to the comment based help for all functions, which it looks like are not included in your code.

I am working on some other updates which will generally update all files, so, whilst updates are sporadic, it is worth checking for any updates.

see ~~Branch [issue-3](https://github.com/pspete/PoShPACLI/tree/issue-3) for updates I am working on~~ [latest merge](https://github.com/pspete/PoShPACLI/commit/a61441631d7599158045b51659861b133f0f4be2) related to #3 (updating all relevant functions to move away from boolean outputs, and moving error messages from debug message stream to error message stream....)

**Comment by pspete** [comment]
#23 has recently been merged. This covered off all of the remaining PSScriptAnalyzer recomendations (implementing SupportsShouldProcess for New-*, Set-*, Remove-* functions).

The actual SupportsShouldProcess logic has been added to [Invoke-PACLICommand.ps1](https://github.com/pspete/PoShPACLI/blob/master/Private/Invoke-PACLICommand.ps1)

If a -whatif or -confirm parameter is passed to a function that supports should process, then this is passed on to Invoke-PACLICommand (the function that does actually carry out the change/executes PACLI).

Now PSScriptanalyzer details a Warning for "PSShouldProcess" on all functions have the ShouldProcess attribute but do not explicitly call ShouldProcess/ShouldContinue. This appears to be purely based on the verb used in the function, and not on the fact that the PSShouldProcess logic is in subsequently called function.

Closing on that basis - thanks for the contribution @BrandonLundt - I look forward to your next one.
