### ISSUE TITLE
PACLI black screens are showing during executions of commands

### ISSUE THREAD

**Issue by SilverminkenNet** [pspete/PoShPACLI#37]
To get rid of these screens, one possible solution to this
Modify Private/Invoke-PACLICommand.ps1

Add these lines 
$PacliProcess.StartInfo.WindowStyle="hidden"
$PacliProcess.startInfo.CreateNoWindow = $True

Before calling: $PacliProcess.start()

I have not encountered noticeable issues with these proposed changes.

**Comment by pspete** [comment]
Hi @SilverminkenNet 

Thanks for reporting; this is not something I see during execution, so have been unaware of this behaviour.

Will test out your suggested fix and implement.
