### ISSUE TITLE
Handling errors.

### ISSUE THREAD

**Issue by TwitchyGit** [pspete/PoShPACLI#39]
On the previous version of PoshPACLI I was handling errors via

$Success=Add-VaultDefinition -sessionID 0 -vault "$VAULTNAME" -address "$VAULTADDR"
if (-not $Success) {write-host -fore Red "ERROR: Failed to load vault address."; exit }

or 
$Success=New-Group -sessionID 0 -vault "$VAULTNAME" -user "$PACLIUSER" -group "$GroupName" -location "\Division"
if (-not $Success) {echo "NOTE: Group $GroupName not created, already exists"}

After updating to the latest version, I've noted Boolean return is now removed, so I've tried to replace with catch/try however its ignored.
I need to handle errors elegantly or in some cases they can just be ignored.  What the recommended method for error handling now?

thanks in advance.

**Comment by TwitchyGit** [comment]
Found your comment on Write-Error, I'm checking that. Thanks.

**Comment by pspete** [comment]
Hi @TwitchyGit - 

You should be able to utilise a try/catch block if you specify `-erroraction Stop` on the function call; this will force any error to be terminating and land you in the catch block.
