### ISSUE TITLE
secure parameter types

### ISSUE THREAD

**Issue by RamblingCookieMonster** [pspete/PoShPACLI#4]
Hi!

It might be worth [avoiding the use of system.string](https://twitter.com/jsnover/status/531103670415679488) for sensitive parameters.

Good alternatives might be SecureString (where Password is used alone) or PSCredential (where a username and password are used).

Awesome that you're writing this, I've been pushing against CyberArk due to the lack of info on controlling it with PowerShell, this would at least make it tolerable if we go that route over expanded Secret Server use!

Cheers!

**Comment by pspete** [comment]
I am 100% with you on this one,it would be a great enhancement - especially seeing as the actual utility  currently uses passwords in plain-text, so would add value in terms of security. I picked up some ideas in this space at the PowerShell European Summit this week.
CyberArk is a good product - but working with the command utility was painful - especially trying to parse the output to do anything meaningful with - Whilst only basic at the moment, the current functionality takes a lot of the complexity out of using the command line interface.

**Comment by ghost** [comment]
Would implementing the ScriptAnalyzer recommendations be something you are interested in? Most of the recommendations are warning or information. For example, Add-File.ps1 has:

RuleName                      |      Severity   |  ScriptName | Line | Message
--------                      |      --------   |  ---------- | ---- | -------
PSUseBOMForUnicodeEncodedFile  |     Warning    |  Add-File.ps1 |   |    Missing BOM encoding for non-ASCII encoded file'Add-File.ps1'
PSUseOutputTypeCorrectly       |     Information | Add-File.ps1 | 75 |   The cmdlet 'Add-File' returns an object of type'System.Boolean' but this type is not declared in theOutputType attribute.
PSUseOutputTypeCorrectly       |     Information | Add-File.ps1 | 81  |  The cmdlet 'Add-File' returns an object of type'System.Boolean' but this type is not declared in the OutputType attribute.

I mention ScriptAnalyzer regarding this issue, as it also notes the $Password parameters should be either secure.string or $Credential.

I would be happy to start working on some of the recommendations. If you think it worth while.

**Comment by pspete** [comment]
Hi @BrandonLundt - thanks for your input.

There certainly are lots of improvements to be made - secure parameter types being the long overdue priority.....

I am not at all against implementing/resolving PSScriptAnalyzer recommendations/findings across the board, they would probably be best dealt with via separate issues (like #3 for the Output Types recomendations for instance).

If you have improvements to make, feel free to work on them - all help appreciated 👍
