### ISSUE TITLE
CAS8N028E CCAGI18NString can't create Collation object. Probably I18N data file is missing.

### ISSUE THREAD

**Issue by prasenjeet** [pspete/PoShPACLI#44]
Hi pspete ,

I am getting below error while running powershell script

**CAS8N028E CCAGI18NString can't create Collation object. Probably I18N data file is missing.**

The issue is coming at line 
$filesList = C:\PACLI\PACLI.exe FILESLIST VAULT='Cloud' USER='PowerShellPACLIUser' SAFE='PasswordManager_info' FOLDER='Root\Policies' OUTPUT'(NAME)'

Is there any equivalent powershell command for FILESLIST ?
I want to get all the file list detail from the safe .
Thanks,
Prasenjeet T

**Comment by pspete** [comment]
Hi @prasenjeet 

Is this an issue with PoShPACLI? 

FILESLIST is available via the Get-PVFileList function

**Comment by prasenjeet** [comment]
Hi Pete ,

Yes . This is the issue while using PoshPACLI.

I am using all other PoSHPACLI commands to open/ close safe PasswordManager_Info except the FILESLIST 
Where I am using normal PACLI command and assigned to power shell variable .
Let me try to see if I can use Get-PVFileList function.

Thanks,
Prasenjeet T

**Comment by pspete** [comment]
I was just checking as I did not recognize the command as part of the module....
I have seen this exact command working in another project recently, so it should work.
If you still get issues, please share the debug output.

**Comment by pspete** [comment]
Example command to save all file details from safe to variable:
```powershell
#Initialise
Initialize-PoShPACLI -pacliFolder D:\PACLI -pacliExe Pacli.exe
#Logon - open safe - get file list
$filesList = Start-PVPACLI | New-PVVaultDefinition -address $vaultIP -vault "Cloud" |
	Connect-PVVault -user $PacliUser -password $password |
	Open-PVSafe -safe PasswordManager_info |
	Get-PVFileList -folder Root\Policies
```

**Comment by pspete** [comment]
Hi @prasenjeet - did you get this to work?

**Comment by prasenjeet** [comment]
Hi Pete,
Thanks for your suggestion . I tried to download new PoShPACLI and it is working .
Earlier I was using different set of PoSHPACLI commands like Start-PACLI, Add-VaultDefinition, Connect-Vault ,Open-Safe . 

Thanks for your help .
Prasenjeet T

**Comment by pspete** [comment]
yes there has been some significant updates recently.... good to hear it is now working.
please let me know if you run into any other issues.
