### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by juler69** [pspete/PoShPACLI#45]
What is available to check if the command was successful or not?
I've tried $rc = <cmd> and testing for 
$rc.Code
$rc.ExitCode
and neither has any value.
I'm trying to build a resilient script :D

**Comment by pspete** [comment]
Hi @juler69 - does #39 help?

try/catch blocks and an appropriate ErrorActionPreference need to be used.

any pacli errors are now written to the error stream (check `$error[0]`)

**Comment by juler69** [comment]
Thanks
