### ISSUE TITLE
Import-Module very slow

### ISSUE THREAD

**Issue by nsleigh** [pspete/PoShPACLI#47]
I noticed that importing the PoShPACLI was very slow, on futher investigation this turned out to be the dot sourcing code. I found this article [https://becomelotr.wordpress.com/2017/02/13/expensive-dot-sourcing](https://becomelotr.wordpress.com/2017/02/13/expensive-dot-sourcing) and implemented the following and it made a significant improvement:
`        Try {`
`            # Dot Source each file`
`            . (`
`                [scriptblock]::Create(`
`                    [io.file]::ReadAllText($_.fullname, [Text.Encoding]::UTF8)`
`                )`
`            )`
`        }`
`        Catch {`
`            Write-Error "Failed to import function $($_.fullname)"`
`        }`

I thought I'd share this in case anyone else has a similar issue. Maybe this could be made the default.

**Comment by TwitchyGit** [comment]
If it does improve the loading times, appreciate if this can be reviewed. I assume its more desirable than compiling the functions into a single file!

**Comment by pspete** [comment]
thanks for this @nsleigh - I will look into your suggestion and implement if it works without issue (unless you fancy submitting a Pull Request?).

@TwitchyGit - the initial commit of this module was over 12k lines - editing was a nightmare!

**Comment by nsleigh** [comment]
Thanks for addressing this, sorry I couldn't offer a Pull Request (the company I work for doesn't allow full internet access).

**Comment by pspete** [comment]
no problem @nsleigh - I work on this purely on my own time for reasons not that dissimilar - otherwise I would have gotten around to it sooner. Thanks for supplying the code!
