### ISSUE TITLE
 CAS8N028E CCAGI18NString can't create Collation object. Probably I18N data file is missing.

### ISSUE THREAD

**Issue by Vichanso** [pspete/PoShPACLI#48]
Link to a similar issue: https://github.com/pspete/PoShPACLI/issues/44

I'm using PoShPACLI to get Files from a Safe. My Vault version is 9.9.0 and my PACLI version is 9.8.0.

I try 2 Windows Server environments to get it works: the one is my lab and the other is a development platform.

I test the command that you recommand (in the link that I point above) and it works well in my lab. But in the other platform, I'm getting this error.

Do you know if the .dll contained in my PACLI (9.8.0) have anything to do with this error?

**Comment by pspete** [comment]
Hi @Vichanso - Thanks for the report.

While testing, I have just run into the same issue as you, which I have not encountered previously.
I have recently updated my lab environment to v9.10 (for [psPAS](https://github.com/pspete/psPAS) development).
I also updated PACLI to version 9.99.0 at the same time (so my environment is not the same as it was when issue #44 was logged).

I switched back to PACLI version 7.20.95 and the command runs without issue.

At this point it looks like ~~PoShPacli~~ `Get-PVFilelist` is not compatible with the newer PACLI-64-bit utility (other PoShPacli functions appear to work - but I have not checked all of them).

Is the version of PACLI the same in both of your environments?
Is using PACLI 7.20.95 an option for you?

**Comment by pspete** [comment]
It is now noted in the README that versions 9.X of PACLI may not work the same way as version 7.2.

To be investigated further......

@Vichanso were you able to confirm if your environments use the same PACLI version?

**Comment by Vichanso** [comment]
By default, EPV have PACLI verison 4.10, in my lab and the development platform.

Since I can have the option to change the version of PACLI, I've decided to use a more recent version of it. For now, I'm going to try testing with this version.

**Comment by pspete** [comment]
So your issue is not with PACLI 9.8?
Be aware that the properties output by v4.10 will likely differ, the regular expressions used to extract the property values may skew the output you see.
Check out one users [edit](https://github.com/kruhmann/PoShPACLI/commit/479a9ac28f794a76466fd891d8680f7a5786fbc5) they had to make to workaround this.

README now updated to include warning about using both PACLI 4.x & 9.x.
Version 7.2 of PACLI was used for development; compatibilty issues can be expected in any other version.

**Comment by misterfifi1** [comment]
Hi, 
I am expecting the same issue but only if the launch the script remotely, it works perfectly locally, so launhed directly from the vault server. 

I know how to fix the issue, as written in the doumntation, you have to: 

> copy this file: icudt42l.dat
> to the c:/windows/syswow64/ folder.

Source: CyberArk Vault CLI Guide and Reference.pdf page 8
