### ISSUE TITLE
Avoiding Invoke-Expression

### ISSUE THREAD

**Issue by RamblingCookieMonster** [pspete/PoShPACLI#5]
Hi again!

Apologies for pestering, feel free to close out these issues.

Noticed you're using [Invoke-Expression](http://blogs.msdn.com/b/powershell/archive/2011/06/03/invoke-expression-considered-harmful.aspx) to kick off the executable - this can be a bit dangerous; it opens you up to injection, and it can give folks who read the code ideas.

It might be worth looking at switching away from Invoke-Expression to [an alternative](http://social.technet.microsoft.com/wiki/contents/articles/7703.powershell-running-executables.aspx).

Cheers!

**Comment by pspete** [comment]
Thanks for the comments, I appreciate the input.
I arrived at Invoke-Expression after failing to get this to work via other means.
Now all of the functions of the PACLI utility are exposed by the module, I will try and develop a different execution method which has less risks associated with it.

**Comment by pspete** [comment]
Invoke-Expression now removed and replaced with an alternative via #18
