### ISSUE TITLE
pacli.exe versions

### ISSUE THREAD

**Issue by ajpgr** [pspete/PoShPACLI#50]
Hi, 

Apologies, I appreciate this isn't strictly related to the PoshPACLI module but in my environment, I'm running an older version of pacli.exe - 7.20.90.28 - can anyone point me to a download location for a later version?

I'm almost certain a 64-bit executable and/or a version 10(?) have been mentioned related to this module previously. 

Any helps appreciated here to point me in the right direction.

Thanks, 

AJ

**Comment by pspete** [comment]
HI @ajpgr 

There is a version newer than 7.2.9 (version 9.99) - it can be downloaded from the CyberArk support site.

FWIW - I have not yet been able to use the new version with the module.

**Comment by ajpgr** [comment]
Thanks @pspete - while I'm here.. did you come across any issues when adding support for the DEFINE keyword with PACLI? I hadn't used CyberArk/pacli prior to being in this environment so unsure whether that's an option required for my environment / there's a better way to do things that doesn't need that option or there were issues with supporting that keyword meaning it doesn't appear as a translated Verb-Noun pair from pacli to PS?

Cheers, 

AJ

**Comment by ajpgr** [comment]
And on triple checking, I'm sorry, I've realised I've just missed it that's all, you can ignore the last comment. 

Thanks, 

AJ
