### ISSUE TITLE
Get-PVUserList returns data in the wrong attributes

### ISSUE THREAD

**Issue by jsuchovsky** [pspete/PoShPACLI#54]
_Your issue may already be reported. Please search existing `issues` before creating one._

## Your Environment

* PowerShell Version: 5.1
* PoShPACLI Version: Pulled on 10/30/2017
* PACLI Version: 4.10.0211
* CyberArk Version: 9.7

## Expected Behaviour

When running $Test = Get-PVUserList -Vault $Vault -User $PACLIUser, it should return user data with each object in the array being a different user.

## Current Behaviour

When running the command, $Test = Get-PVUserList -Vault $Vault -User $PACLIUser, it returns data in the wrong columns, with more than one user being in one object of the array.

Username                  Location              Disabled           LDAPUser         GWAccount           UsedQuota
--------                  --------              --------           --------         ---------           ---------
Master                    \                     NO                 NO               NO                  0
-1                                              USER               NO               NO                  \System
71904                                           2                  NO               USER
\                         NO                    0                  YES              3
                          NO                    Batch              USER             1                   NO
                          NO                    -1                 5                DR                  NO
NO                        NO                    0                  1                -1                  NO
NO                        GROUP                 \                  Auditors         0                   NO
NO                        8                                        -1               \System             GROUP
NO                        1                                        0                                    9
GROUP                     Vault Admins          NO                 \System                              1
11                        -1                    NO                                  NO                  Notification...
0                         0                     NO                                  NO                  -1
PasswordManager           \                     NO                 NO               NO                  0
-1                                              USER               NO               NO                  \
0                                               16                 NO               USER
\                         NO                    0                  NO               17
                          NO                    PVWAGWAccounts     GROUP            0                   NO

## Steps to Reproduce (for bug reports)

1 . Log in using,  Connect-PVVault -Vault $Vault -User $PACLIUser -LogonFile $Credfile

2 . Run, Get-PVUserList -Vault $Vault -User $PACLIUser

3 .

4 .

## Sample Output

Username                  Location              Disabled           LDAPUser         GWAccount           UsedQuota
--------                  --------              --------           --------         ---------           ---------
Master                    \                     NO                 NO               NO                  0
-1                                              USER               NO               NO                  \System
71904                                           2                  NO               USER
\                         NO                    0                  YES              3
                          NO                    Batch              USER             1                   NO
                          NO                    -1                 5                DR                  NO
NO                        NO                    0                  1                -1                  NO
NO                        GROUP                 \                  Auditors         0                   NO
NO                        8                                        -1               \System             GROUP
NO                        1                                        0                                    9
GROUP                     Vault Admins          NO                 \System                              1
11                        -1                    NO                                  NO                  Notification...
0                         0                     NO                                  NO                  -1
PasswordManager           \                     NO                 NO               NO                  0
-1                                              USER               NO               NO                  \
0                                               16                 NO               USER
\                         NO                    0                  NO               17
                          NO                    PVWAGWAccounts     GROUP            0                   NO

## Context

Was trying to use it to see if users already have an account in CyberArk.

**Comment by pspete** [comment]
Hi @jsuchovsky.
Yes, different versions of PACLI do not produce the same output.
PACLI 7.2 was used for development of this module, I do not have version 4.1 available to me to replicate the issue you describe.

I think @kruhmann has resolved this in their fork at [this link](https://github.com/kruhmann/PoShPACLI/commit/479a9ac28f794a76466fd891d8680f7a5786fbc5#diff-7c4f325cfb84e5c3636e6dab98d07b74)

**Comment by jsuchovsky** [comment]
Pete,

Thanks,  I updated to 9.7 and the issue went away.

Josh

**Comment by pspete** [comment]
Glad it is sorted
