### ISSUE TITLE
Get-PVUser doesn't return Group membership

### ISSUE THREAD

**Issue by craigpryor** [pspete/PoShPACLI#57]
_Your issue may already be reported. Please search existing `issues` before creating one._

## Your Environment

* PowerShell Version: 5.1.177134.407
* PoShPACLI Version: Just downloaded latest master
* PACLI Version: 5x
* CyberArk Version: 7.7

Hi guys, maybe not so much an issue than a question, but i cannot find a way to raise questions.

I am trying to identify what groups a particular user is a member of . I cant seem to find a way to do this. Should Get-PVUser return this information? When I am in the GUI, I can see the 'Member of' tab which has all the information expected.

Thanks

**Comment by pspete** [comment]
From memory, I think the only way is to query each group with `Get-PVGroupMember`.
It does not look like `Get-PVUser` returns any group membership information.

**Comment by craigpryor** [comment]
Hi Pete, thanks for the response.
In this case, is there a way to return a list of all groups? I can then iterate through them and look for my user.
I couldn't find a way to to pull all group names back either.
Thanks

**Comment by craigpryor** [comment]
Also, why i have you here, is there a way to return all existing sessions please?
So far I can only find a way to create a new session/token but not see any existing. Or does that session only exist within the variable it has been defined/captured in?

I want to make sure all of my sessions have been successfully stopped/terminated at the end of the script.

Thanks

**Comment by pspete** [comment]
> Hi Pete, thanks for the response.
> In this case, is there a way to return a list of all groups? I can then iterate through them and look for my user.
> I couldn't find a way to to pull all group names back either.
> Thanks

Group Names are included in the output of `Get-PVUserList` - then I think you need to use `Get-PVGroup` to determine if it is a group or not.

**Comment by pspete** [comment]
> Also, why i have you here, is there a way to return all existing sessions please?
> So far I can only find a way to create a new session/token but not see any existing. Or does that session only exist within the variable it has been defined/captured in?
> 
> I want to make sure all of my sessions have been successfully stopped/terminated at the end of the script.
> 
> Thanks

There is no module (or pacli) function to do this.
Each time `Start-PVPacli -sessionID ###` is run, a new pacli.exe process is created.
If `Get-Process pacli` returns results, then there are likely have sessions open.
Either kill the process or run `Stop-PVPacli -sessionID ###`
