### ISSUE TITLE
Issue with PV-findfile.. not able to find all the objects using this command

### ISSUE THREAD

**Issue by User9176** [pspete/PoShPACLI#59]
_Your issue may already be reported. Please search existing `issues` before creating one._

## Your Environment

* PowerShell Version:  5.1
* PoShPACLI Version: 0.2.1
* PACLI Version:  9.9.5
* CyberArk Version:  9.10

## Expected Behaviour

PV-FindFiles should be able to find all the objects in a safe. I am trying to fetch “Safename” with “SafeFileCategories” values.

Below is the command i am using,

```powershell
Find-PVFile -vault “vault” -user “user” -safe “safe” -folder “folder” -deletedOption “WITHOUT_DELETED” -includeFileCategories “yes” -fileCategoriesSeperator “_#_” | select @{expression={$_.Safe}; label=‘Safes’,@{expression={$_.FileCategories}; label=‘SafeFileCategories’} | export-csv “path” -NoTypeInformation
```

## Current Behaviour

1. Able to see only few objects (like 10 out of 400) Missing to find few file categories from the safe
2. Also, it is giving some random values (like passwordmanager, - -, 0,1,-3,-4.....) instead of exact safe and file categories.

## Possible Solution

Please suggest me if anything am missing in the command

## Steps to Reproduce (for bug reports)

1 .

2 .

3 .

4 .

**Comment by pspete** [comment]
@User9176 - provide the required details, as per the issue template.

**Comment by User9176** [comment]
Hello Pete,
I have updated the info as suggested, please look into it and let me know if anything is missing from my end. Thanks for your help!

**Comment by pspete** [comment]
The `includeFileCategories` parameter is a switch - so will not accept "yes" as an argument.

double check the output of the `Find-PVFile` command:

```powershell
Find-PVFile -vault “vault” -user “user” -safe “safe” -folder “folder” -deletedOption “WITHOUT_DELETED” -includeFileCategories -fileCategoriesSeperator “_#_”
```
- Are the details included as expected?
- Set `$DebugPreference` to `Continue` & run the command. 
  - How many properties returned for each file?

compare against the native output of PACLI:
```powershell
FINDFILES safe="safe" folder="folder" deletedOption=WITHOUT_DELETED includeFileCategories=YES fileCategoriesSeparator="_#_" user="user" vault="vault" OUTPUT (ALL,ENCLOSE)
```
- Are all of the expected details returned?

As per the [prerequisites for the module](https://github.com/pspete/PoShPACLI#prerequisites), PACLI 7.2 was used for development, your mileage may vary with any other version.

**Comment by pspete** [comment]
Briefly tested with [PoShPACLI 1.0](https://www.powershellgallery.com/packages/PoShPACLI/1.0.0) & Pacli 9.99 - was unable to reproduce

```powershell
PS C:\> $token | Find-PVFile -safe 3_testsafe_100_XLZ -folder root -fileCategoriesSeparator "_#_" | select safe, filecategories
Safe               FileCategories
----               --------------
3_TestSafe_100_XLZ LogonDomain:SOMEDOMAIN_#_DeviceType:Operating System_#_PolicyID:Z_WINDOMAIN_OFF_#_Address:SOMEDOMAIN.COM_#_UserName:dpvxbnci_#_CreationMethod:PVWA_#_  
3_TestSafe_100_XLZ LogonDomain:SOMEDOMAIN_#_DeviceType:Operating System_#_PolicyID:Z_WINDOMAIN_OFF_#_Address:SOMEDOMAIN.COM_#_UserName:fzowlnba_#_CreationMethod:PVWA_#_…
```

**Comment by User9176** [comment]
Hi Pete,

I tried removing “yes” in my previous script as well - but it didn’t worked
for me. Now it worked.

Also, can you please let me know your thoughts on below points:

1. Using “Find-PVfile” getting few of the account usages (NOT ALL) as well
- which I don’t need

2. I want to use -fileCategoryValueSeperator “_%_” as well. But it is
throwing “parse error, expecting ‘;’ “ error

3. Using “Get-PVSafeList” command - I am getting deleted safes as well -
which i don’t need.

How can I fix above issues.. please suggest!!
Thanks much for your help.

**Comment by pspete** [comment]
@User9176 - can you provide examples to illustrate what you are/are not expecting?

For things you do not need, it's up to you to disregard them - it is not a feature of the module

**Comment by User9176** [comment]
Sure.

1. Using Find-PVFile ( from the command given by you) I only need Safe and
SafeFileCategories for all the accounts in the vault. But only for few
accounts, I am getting account usages as well (which are not required)

2. I want parameter filecategoryvalueseperator as “_#_”  via PoShPACLI as
below. But below command is throwing me the parse error

Find-PVFile -vault “vault” -user “user” -safe “safe” -folder “Root”
-deletedOption “Without_Deleted” -FileCategoryValueSeperator “_#_”

If i try via native pacli using below command its working fine,

Pacli FindFiles vault=“vault” user=“user” safe=“safe” folder=Root
deletedoption=“Without_Deleted” FileCategoryValueSeperator=“_#_”

3. I am trying to see all the safes via Get-PVSafeList. But, am getting
deleted safes as well ( as we have retention period of 30 days to get the
safes deleted completely) . So is there any parameter to exclude deleted
safes ? Below is the command am using,

Get-PVsafeList -vault “vault” -user “user”

Please let me know if you need any further information from me.

Thank you!

**Comment by pspete** [comment]
All the module does is parse the strings returned from Pacli.exe and returns them as properties of a powershell object.

1. If you are using the command from the above `Find-PVFile` example, the final `select` statement disregards everything except the `safe` & `filecategories` properties; the information is being returned to you as it is present in the value of these properties.

2. [The same example also shows that there is no problem using "\_#\_" as a seperator](https://github.com/pspete/PoShPACLI/issues/59#issuecomment-514142869).

3. The only other parameters for `Get-PVSafeList` are `location` & `includeSubLocations`, in line with the SAFESLIST Pacli command.

**Comment by User9176** [comment]
Thanks Pete for the response!

2. The example we tried is for “fileCategoriesSeperator”. Now. I’m looking
for “fileCategoryValueSeperator”

Below command is throwing parse error—

Find-PVFile -vault “vault” -user “user” -safe “safe” -folder “root”
-deletedOption “Without_Deleted” -fileCategoryValueSeperator “_@_”

And below native pacli command is working fine—

PACLI FINDFILES vault=“vault” user=“user” safe=“safe” folder=“root”
deletedoption=“without_deleted” filecategoryvalueseperator=“_@_”

Please help me.
Thank you

**Comment by User9176** [comment]
Hi Pete,

This is little urgent. Can you please suggest on this?
Thanks much for your help.

**Comment by pspete** [comment]
Oh OK, I'll get on it right away...
Fixed in [1.1.4](https://www.powershellgallery.com/packages/PoShPACLI/1.1.4)
![image](https://user-images.githubusercontent.com/10600090/61802110-d9a5f380-ae27-11e9-9e03-461291bbe6cc.png)

**Comment by User9176** [comment]
Pete,
Thank you for the quick turnaround on this.

I have downloaded newer version ‘1.4.1’, but new parameter is not updated
in power shell console. Error says “A parameter cannot be found that
matches parameter name ‘fileCategoryValuesSeperator’

Any suggestions?
Thanks much for your help.

**Comment by pspete** [comment]
If you are using v1.1.4, the `fileCategoryValuesSeparator` parameter is there: https://github.com/pspete/PoShPACLI/blob/master/PoShPACLI/Functions/FoldersFiles/Find-PVFile.ps1#L380
![image](https://user-images.githubusercontent.com/10600090/61813981-ed108900-ae3e-11e9-8391-5f7574cfe6c0.png)

**Comment by User9176** [comment]
Hi Pete,

Thank you for the help- its working fine now!
One more suggestion needed from you is -

If I run command, OwnersList via PACLI - It’s taking approximately 1hour to
execute the command

And if i run command, Get-PVSafeOwner - It’s taking more than 6 hours to
execute the command.

And am fetching same data by using both the commands.

Why it is taking this much longer via Poshpacli? Any suggestions to reduce
the execution time?

Please advise the possible options to reduce the time?

Thanks in advance Pete.
