### ISSUE TITLE
PoShPACLI commands taking much time for execution than PACLI

### ISSUE THREAD

**Issue by User9176** [pspete/PoShPACLI#61]
Your Environment:

PowerShell Version: 7.2
PoShPACLI Version: 1.1.4
PACLI Version: 9.9.5
CyberArk Version: 9.10

## Expected Behaviour

If I run command, OwnersList via PACLI - It’s taking approximately 1hour to
execute the command

OwnersList vault="vault" user="user" safepattern="*" ownerpattern="*" output (username,safename,Accesslevel) > SafeOwnersList.csv

And if i run command, Get-PVSafeOwner - It’s taking more than 6 hours to
execute the command.

Get-PVSafeOwner -Vault "vault" -User "user" -safepattern * -ownerpattern * | select @{expression={$_.Username}; label='Owners Of The Safes'},@{expression={$_.safename}; label='Safes'  },@{expression={$_.Accesslevel}; label='AccessOfEachSafe'} | Export-csv SafeOwnersList.csv

Please advice me the possible options to reduce the execution time 

Thanks,
Pete!

**Comment by User9176** [comment]
Hi Pete,

Any advice on above issue would be really helpful - Please help me!!

Thanks in advance!

**Comment by pspete** [comment]
Hi @User9176 - I likely won't get a chance to look at this in any depth for a while.

I did a quick check;  the `select` statement with calculated properties adds significant overhead (approximately doubling the time taken for the command to complete):

PoShPACLI has to process the output of PACLI, so execution time will always be longer than PACLI alone. There will also be additional overhead resulting from the internal module workflow (executing the command, parsing the returned data etc).

It is therefore feasible that such a query, which takes so long to complete anyway, is further compounded by the additional processing required by the module (on top of the time taken to process your code).

You are welcome to investigate the `Start-ClientProcess`, `Invoke-PACLICommand`, `ConvertTo-ParameterString` & `ConvertFrom-PacliOutput` functions to determine improvements which can be made to improve execution times.

**Comment by pspete** [comment]
@User9176 - I found some time to take a look at this.

There are some syntax issues in your select statement; once these are rectified the time taken to execute the command against the same sample of safes decreases significantly:

```powershell
#Original Command - executes in ~30 seconds
Measure-Command -Expression {
    Get-PVSafeOwner -Vault "vault" -User "user" -safepattern * -ownerpattern * | select @{expression={$.Username}; label='Owners Of The Safes'},@{expression={$.safename}; label='Safes' },@{expression={$_.Accesslevel}; label='AccessOfEachSafe'}
} | select totalseconds

#This executes in <1 second
Measure-Command -Expression {
    Get-PVSafeOwner -Vault "vault" -User "user" -safepattern * -ownerpattern * | select @{expression={$_.Username}; label='Owners Of The Safes'},@{expression={$_.safename}; label='Safes' },@{expression={$_.Accesslevel}; label='AccessOfEachSafe'}
} | select totalseconds

```

**Comment by pspete** [comment]
@User9176 with the release of PoShPACLI 2.0, I am now closing this issue.

The internal mechanics of the module have been updated and execution times are now significantly reduced; see the results of `Measure-Command` for the old and new versions below:

Old Version (1.1.4)

``` powershell
PS>Import-Module PoShPACLI -RequiredVersion 1.1.4                                                                       
PS>$token = Start-PVPacli -sessionID 303                                                                                
PS>$token = $token | New-PVVaultDefinition -vault SomeVault -address zzEPV1                                             
PS>$token = $token | Connect-PVVault -user $($CACreds.UserName) -password $($CACreds.Password)                          
                                                                                                            
PS>Measure-Command -Expression {$token | Get-PVSafeOwner -safePattern * -ownerPattern *} | Select-Object TotalSeconds   
TotalSeconds
------------
  80.6836571
                                                                                                                
PS>Measure-Command -Expression {$token | Get-PVUserList} | Select-Object TotalSeconds                                   
TotalSeconds
------------
   2.4337341
```

New Version (2.0.20)

``` powershell
PS>Import-Module PoShPACLI -RequiredVersion 2.0.20                                                                      
PS>Start-PVPacli -sessionID 303                                                                                         
PS>New-PVVaultDefinition -vault SomeVault -address zzEPV1                                                               
PS>Connect-PVVault -user $($CACreds.UserName) -password $($CACreds.Password)     
                                       
PS>Measure-Command -Expression {Get-PVSafeOwner -safePattern * -ownerPattern *} | Select-Object TotalSeconds            
TotalSeconds
------------
   2.2139775
                                                         
PS>Measure-Command -Expression {Get-PVUserList} | Select-Object TotalSeconds                                            
TotalSeconds
------------
   0.3583596
```

As 2.0 is a Major Version update, there are breaking changes, so take note of the details in the [Changelog](https://github.com/pspete/PoShPACLI/blob/master/CHANGELOG.md) as some update to your code will be required.

Feel free to comment if you want this reopened - would be curious to know the execution time you now get for your query.
