### ISSUE TITLE
Hide-SecretValue Requires input, empty string causes error

### ISSUE THREAD

**Issue by jbalcorn** [pspete/PoShPACLI#66]
## Your Environment

* PowerShell Version: 5
* PoShPACLI Version: 2.0.20
* PACLI Version: 11.1
* CyberArk Version: 11.1

## Expected Behaviour

Trying to run https://github.com/UberKitten/Export-PendingAccounts When it calls Start-PVPacli an error is thrown because Hide-SecretValue is called with an empty string. 

## Current Behaviour

Error Thrown

## Possible Solution

 It should check for empty string and return silently.

## Steps to Reproduce (for bug reports)

1 . Install PoShPACLI and Export-PendingAccounts

2 . Run Export-PendingAccounts

3 . Error!

## Sample Output

VERBOSE: Loading module from path 'C:\Users\xxxxxxx\Documents\WindowsPowerShell\Modules\PoShPACLI\PoShPACLI.psd1'.
VERBOSE: Importing function 'Add-PVCTLCertificate'.
VERBOSE: Importing function 'Add-PVExternalUser'.
VERBOSE: Importing function 'Add-PVFile'.
VERBOSE: Importing function 'Add-PVFileCategory'.
VERBOSE: Importing function 'Add-PVGroupMember'.
VERBOSE: Importing function 'Add-PVPasswordObject'.
VERBOSE: Importing function 'Add-PVPreferredFolder'.
VERBOSE: Importing function 'Add-PVRule'.
VERBOSE: Importing function 'Add-PVSafeGWAccount'.
VERBOSE: Importing function 'Add-PVSafeOwner'.
VERBOSE: Importing function 'Add-PVTrustedNetworkArea'.
VERBOSE: Importing function 'Clear-PVSafeHistory'.
VERBOSE: Importing function 'Clear-PVUserHistory'.
VERBOSE: Importing function 'Close-PVSafe'.
VERBOSE: Importing function 'Connect-PVVault'.
VERBOSE: Importing function 'Disable-PVTrustedNetworkArea'.
VERBOSE: Importing function 'Disconnect-PVVault'.
VERBOSE: Importing function 'Enable-PVTrustedNetworkArea'.
VERBOSE: Importing function 'Find-PVFile'.
VERBOSE: Importing function 'Get-PVConfiguration'.
VERBOSE: Importing function 'Get-PVCTL'.
VERBOSE: Importing function 'Get-PVCTLCertificate'.
VERBOSE: Importing function 'Get-PVFile'.
VERBOSE: Importing function 'Get-PVFileActivity'.
VERBOSE: Importing function 'Get-PVFileCategory'.
VERBOSE: Importing function 'Get-PVFileList'.
VERBOSE: Importing function 'Get-PVFileVersionList'.
VERBOSE: Importing function 'Get-PVFolder'.
VERBOSE: Importing function 'Get-PVGroup'.
VERBOSE: Importing function 'Get-PVGroupMember'.
VERBOSE: Importing function 'Get-PVLDAPBranch'.
VERBOSE: Importing function 'Get-PVLocation'.
VERBOSE: Importing function 'Get-PVNetworkArea'.
VERBOSE: Importing function 'Get-PVPasswordObject'.
VERBOSE: Importing function 'Get-PVRequest'.
VERBOSE: Importing function 'Get-PVRequestStatus'.
VERBOSE: Importing function 'Get-PVRule'.
VERBOSE: Importing function 'Get-PVSafe'.
VERBOSE: Importing function 'Get-PVSafeActivity'.
VERBOSE: Importing function 'Get-PVSafeEvent'.
VERBOSE: Importing function 'Get-PVSafeFileCategory'.
VERBOSE: Importing function 'Get-PVSafeList'.
VERBOSE: Importing function 'Get-PVSafeLog'.
VERBOSE: Importing function 'Get-PVSafeOwner'.
VERBOSE: Importing function 'Get-PVTrustedNetworkArea'.
VERBOSE: Importing function 'Get-PVUser'.
VERBOSE: Importing function 'Get-PVUserActivity'.
VERBOSE: Importing function 'Get-PVUserList'.
VERBOSE: Importing function 'Get-PVUserPhoto'.
VERBOSE: Importing function 'Get-PVUserSafeList'.
VERBOSE: Importing function 'Import-PVVaultDefinition'.
VERBOSE: Importing function 'Lock-PVFile'.
VERBOSE: Importing function 'Lock-PVUser'.
VERBOSE: Importing function 'Move-PVFile'.
VERBOSE: Importing function 'Move-PVFolder'.
VERBOSE: Importing function 'Move-PVNetworkArea'.
VERBOSE: Importing function 'New-PVFolder'.
VERBOSE: Importing function 'New-PVGroup'.
VERBOSE: Importing function 'New-PVLDAPBranch'.
VERBOSE: Importing function 'New-PVLocation'.
VERBOSE: Importing function 'New-PVLogonFile'.
VERBOSE: Importing function 'New-PVNetworkArea'.
VERBOSE: Importing function 'New-PVNetworkAreaAddress'.
VERBOSE: Importing function 'New-PVPassword'.
VERBOSE: Importing function 'New-PVSafe'.
VERBOSE: Importing function 'New-PVSafeFileCategory'.
VERBOSE: Importing function 'New-PVUser'.
VERBOSE: Importing function 'New-PVVaultDefinition'.
VERBOSE: Importing function 'Open-PVSafe'.
VERBOSE: Importing function 'Remove-PVCTLCertificate'.
VERBOSE: Importing function 'Remove-PVFile'.
VERBOSE: Importing function 'Remove-PVFileCategory'.
VERBOSE: Importing function 'Remove-PVFolder'.
VERBOSE: Importing function 'Remove-PVGroup'.
VERBOSE: Importing function 'Remove-PVGroupMember'.
VERBOSE: Importing function 'Remove-PVLDAPBranch'.
VERBOSE: Importing function 'Remove-PVLocation'.
VERBOSE: Importing function 'Remove-PVNetworkArea'.
VERBOSE: Importing function 'Remove-PVNetworkAreaAddress'.
VERBOSE: Importing function 'Remove-PVPreferredFolder'.
VERBOSE: Importing function 'Remove-PVRequest'.
VERBOSE: Importing function 'Remove-PVRule'.
VERBOSE: Importing function 'Remove-PVSafe'.
VERBOSE: Importing function 'Remove-PVSafeFileCategory'.
VERBOSE: Importing function 'Remove-PVSafeGWAccount'.
VERBOSE: Importing function 'Remove-PVSafeOwner'.
VERBOSE: Importing function 'Remove-PVTrustedNetworkArea'.
VERBOSE: Importing function 'Remove-PVUser'.
VERBOSE: Importing function 'Rename-PVLocation'.
VERBOSE: Importing function 'Rename-PVNetworkArea'.
VERBOSE: Importing function 'Rename-PVSafe'.
VERBOSE: Importing function 'Rename-PVUser'.
VERBOSE: Importing function 'Reset-PVFile'.
VERBOSE: Importing function 'Reset-PVSafe'.
VERBOSE: Importing function 'Restore-PVFile'.
VERBOSE: Importing function 'Restore-PVFolder'.
VERBOSE: Importing function 'Send-PVMailMessage'.
VERBOSE: Importing function 'Set-PVConfiguration'.
VERBOSE: Importing function 'Set-PVFileCategory'.
VERBOSE: Importing function 'Set-PVGroup'.
VERBOSE: Importing function 'Set-PVLDAPBranch'.
VERBOSE: Importing function 'Set-PVLocation'.
VERBOSE: Importing function 'Set-PVObjectValidation'.
VERBOSE: Importing function 'Set-PVRequestStatus'.
VERBOSE: Importing function 'Set-PVSafe'.
VERBOSE: Importing function 'Set-PVSafeFileCategory'.
VERBOSE: Importing function 'Set-PVSafeNote'.
VERBOSE: Importing function 'Set-PVSafeOwner'.
VERBOSE: Importing function 'Set-PVUser'.
VERBOSE: Importing function 'Set-PVUserPassword'.
VERBOSE: Importing function 'Set-PVUserPhoto'.
VERBOSE: Importing function 'Start-PVPacli'.
VERBOSE: Importing function 'Stop-PVPacli'.
VERBOSE: Importing function 'Unlock-PVFile'.
VERBOSE: Importing function 'Unlock-PVUser'.
VERBOSE: Importing function 'Write-PVSafeEvent'.

Cannot bind argument to parameter 'InputValue' because it is an empty string.
At line:44 char:12
+ ...   $Return = Invoke-PACLICommand $Script:PV.ClientPath INIT $($PSBound ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-PACLICommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Invoke-PACLICommand

**Comment by pspete** [comment]
As far as I am aware that particular tool would need to be updated to work with the latest version of PoShPACLI.
you could try the previous PoShPACLI version: https://www.powershellgallery.com/packages/PoShPACLI/1.1.4

Note that the syntax will be slightly different due to the changes between PoShPACLI v1 & v2

**Comment by jbalcorn** [comment]
I discovered that.  I am submitting a pull request to that author.

**Comment by jbalcorn** [comment]
When I do a Start-PVPacli without any parameters, the Hide-SecretValue still blows up on the empty parameter string, even just running the command in powershell.  Is the SessionID parameter required? It should default to 0, but your examples always pass a SessionID.    If I set the parameter to Mandatory = $false, then start-pvpacli works just fine.

**Comment by pspete** [comment]
👍 Thank You @jbalcorn 
Will implement the fix you describe.

**Comment by jbalcorn** [comment]
Cool!  I am submitting pull requests to update the Export-PendingAccount.ps1 to work with 2.0.20.  https://github.com/jbalcorn/Export-PendingAccounts
