### ISSUE TITLE
Pacli Script to release locked account automatically

### ISSUE THREAD

**Issue by nawazsarwar124** [pspete/PoShPACLI#70]
Hello pspete,

I hope you are fine. I am looking for pacli script which can automatically release the locked account once in 24 hours. This job is done by user passwordmanager but i have to migrate from version v7 so i need to shutdown the cpm. The problem is if i shutdown cpm then it will not unlock account. Can you please suggest some solution or if you have any script which i can use for this purpose.

Thanks,

**Comment by pspete** [comment]
[UNLOCKFILE](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PACLI/Folder-and-File-Functions.htm?tocpath=Developer%7CCommand%20Line%20Interface%20(PACLI)%7C_____6#UnlockFile) maybe?

**Comment by pspete** [comment]
inactive issue - closing
