### ISSUE TITLE
Is  is possible to capture 1 user's safe membership?

### ISSUE THREAD

**Issue by engkeen-source** [pspete/PoShPACLI#71]
It is possible to achieve in CyberArk pacli.

OwnerSafesList

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PACLI/Safe-Functions.htm#OwnerSafesList

**Comment by pspete** [comment]
Sure, it is already detailed in the project's readme.
The command is 'Get-PVUserSafeList'
