### ISSUE TITLE
Issue Stop-PVPacli if more session is made. Can’t close other pacli.exe they will hang in task manager

### ISSUE THREAD

**Issue by melsby** [pspete/PoShPACLI#74]
_Your issue may already be reported. Please search existing `issues` before creating one._

## Your Environment

* PowerShell Version: 5.1 build 14409 revision 1027
* PoShPACLI Version: 2.1.27
* PACLI Version: v7.20.95
* CyberArk Version: v8.0.0

## Expected Behaviour
Close Pacli.exe for each session.

## Current Behaviour
Will only close one of the sessions and leave all other Pacli.exe in task manager.
They never be closed.

## Possible Solution
Add sessionID to Stop-PVPacli.ps1
[CmdLetBinding(SupportsShouldProcess)]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSShouldProcess", "", Justification = "ShouldProcess handling is in Invoke-PACLICommand")]
    param(
    		[Parameter(
			Mandatory = $False,
			ValueFromPipelineByPropertyName = $True)]
		    [int]$sessionID
    )

    $Null = Invoke-PACLICommand -PacliEXE $Script:PV.ClientPath -PacliCommand TERM -CommandParameters $($PSBoundParameters | ConvertTo-ParameterString -NoVault -NoUser)

} 

## Steps to Reproduce (for bug reports)

Open 2 powershell ISE and make this program, with sessionID 1 and 2
vaultUser=''
$pass=’'
$vaultIp=’’
$vaultPort=''
$ClientPath = ’’
$Password = ConvertTo-SecureString $pass -AsPlainText -Force
Import-Module PoShPACLI
Set-PVConfiguration -ClientPath $ClientPath
Start-PVPacli -sessionID 1
#wait until you have start a second session with sessionID 2 
Stop-PVPacli 

You will get error the second time you try Stop-PVPacli

## Sample Output
Invoke-PACLICommand : Cannot communicate with PACLI server. Issue PACLI init.

**Comment by pspete** [comment]
Hi @melsby ,

Not seeing this behaviour, `sessionID` is set as a Script scope variable in each PowerShell ISE workspace, and passed to each invocation of the `Stop-PVPacli` command (see the debug output):

## ISE 1
```powershell
 > Start-PVPACLI -sessionID 1
DEBUG: PACLI Command: INIT sessionID=1
 > Stop-PVPacli
DEBUG: PACLI Command: TERM sessionID=1
```

## ISE 2
```powershell
 > Start-PVPACLI -sessionID 2
DEBUG: PACLI Command: INIT sessionID=2
 > Stop-PVPacli
DEBUG: PACLI Command: TERM sessionID=2
```

The `Set-PVConfiguration` command can be used to set the context of the PACLI session with which you want to interact.

```powershell
 > Start-PVPacli -sessionID 1
DEBUG: PACLI Command: INIT sessionID=1
 > Start-PVPacli -sessionID 2
DEBUG: PACLI Command: INIT sessionID=2
 > Get-Process PACLI
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                 
-------  ------    -----      -----     ------     --  -- -----------                                                 
    214      11     8592      11620       0.08   6984   1 Pacli                                                       
    214      11     8564      11600       0.09  21384   1 Pacli                                                       

 > Stop-PVPacli
DEBUG: PACLI Command: TERM sessionID=2
 > Set-PVConfiguration -sessionID 1
 > Stop-PVPacli
DEBUG: PACLI Command: TERM sessionID=1
 > Get-Process PACLI
```

**Comment by pspete** [comment]
@melsby - closing as believe the above provides answers for the behaviour observed.
Leave a comment not :)
