### ISSUE TITLE
How to use parameters

### ISSUE THREAD

**Issue by rofo68** [pspete/PoShPACLI#8]
Hy,
i have to add new passwordobjects to cyberark. After some searchs i found your module but i'm not able to use the functions. Only functions without Parameters works, all other give me "parse error". Do you have some examples how to add a passwordobjects?
Thanks in advance
roko

**Comment by pspete** [comment]
Hi roko,

There is another issue/bug open around the "parse error", I am not sure if it is the same as the one which you are experiencing.

At a high level, the method to use the module to add a password object to a safe is shown in the below code (It is an identical process to using the PACLI tool on its own): 

```
#locate/set path to PACLI executable
Initialize-PoShPACLI

#Start PACLI Executable
Start-PACLI

#Define Vault
Add-VaultDefinition -vault "VAULT" -address "vaultAddress"

#Logon to vault
Connect-Vault -vault "VAULT" -user "User" -logonFile "credfile.xxx"

#Open Safe
Open-Safe -vault "VAULT" -user "User" -safe "SAFE_Name"

#Add Password to Safe
Add-PasswordObject -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -password "Password_String"

#Add Device Type for password
Add-FileCategory -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -category "DeviceType" -value "Device_Type"

#Add PolicyID for password
Add-FileCategory -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -category "PolicyID" -value "Policy_Name"

#Add Logon Domain for password
Add-FileCategory -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -category "LogonDomain" -value "Domain_Name"

#Add Address for password
Add-FileCategory -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -category 'Address' -value "Address_Value"

#Add UserName for password
Add-FileCategory -vault "VAULT" -user "User" -safe "SAFE_Name" -folder "Root" -file "passwordFile" -category "UserName" -value "Account_Name"

#Close Safe
Close-Safe -vault "VAULT" -user "User" -safe "SAFE_Name"

#Logoff From Vault
Disconnect-Vault  -vault "VAULT" -user "User"

#Stop Pacli process
Stop-PACLI
```

Let me know how you get on. I have not done any work or testing on this in quite a while due to other commitments, any feedback is appreciated.

psPete

**Comment by rofo68** [comment]
Hy Pete,

than you for your quick answer. After running Initialize-PoShPACLI and Start-PaCLI i get an error when i try to define vault:
Add-VaultDefinition -vault "Vault" -address "10.65.115.47" -Verbose -Debug
VERBOSE: Defining Vault
DEBUG: Processing Bound Parameters
DEBUG: vault=Vault address=10.65.115.47
DEBUG: LastExitCode: -1
VERBOSE: parse error, expecting `__PACLI_STRING'
False
Any ideas?
roko

**Comment by pspete** [comment]
As per issue #7 - it is probably down to the numeric value for the address which are required to be wrapped in quotes to avoid the parse error.

Either, try and use a DNS name for the vault (this works for me - but is obviously environment specific), or make the below edit to the Add-VaultDefinition function, which will add quotes around the values passed to the utility:

Original:

```
$vaultDefinition = (Invoke-Expression "$pacli DEFINE $($PSBoundParameters.getEnumerator() | ConvertTo-ParameterString)" -ErrorAction SilentlyContinue) 2>&1
```

Updated:

```
$vaultDefinition = (Invoke-Expression "$pacli DEFINE $($PSBoundParameters.getEnumerator() | ConvertTo-ParameterString -quoteOutput)" -ErrorAction SilentlyContinue) 2>&1
```

The debug output should show you the parameter values being passed, with added quotes.

**Comment by rofo68** [comment]
Hi Pete,
have now my script ready to add passwordobjects, but i have two issues:
When i open safe, PACLI returnes an error: "Unrecognized character" and return code 0.
We have some parameter (filename and devicetype) with a blank, do you have any idea who can i pass this parameter?
Thank you for Feedback
roko

**Comment by pspete** [comment]
Hi Roko - I don't have access to an environment that I can test in at the moment - without this it is a bit difficult to assist. Is it possible to share the verbose/debug output related to the error?

**Comment by rofo68** [comment]
Hi Pete,
the first issue is not really a problem, because pacli return with exitcode 0:
Open-Safe -vault $Vault -user $User -safe $SafeWin -Verbose -Debug
DEBUG: Processing Bound Parameters
DEBUG: "vault=""Vault""" "user=""PacliScriptUser""" "safe=""COM_DE_Win"
C:\COM_Services\SUP-026\Pacli\Pacli55\PACLI.EXE : Unrecognized character
At line:1 char:1
- C:\COM_Services\SUP-026\Pacli\Pacli55\PACLI.EXE OPENSAFE "vault=""Vault""" "user ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (Unrecognized character:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

DEBUG: LastExitCode: 0
DEBUG: Parameter Value #1: "COM_DE_Win"
DEBUG: Parameter Value #2: "YES"
DEBUG: Parameter Value #3: "Wed Oct 14 00:49:16 2015"
DEBUG: Parameter Value #4: "YES"
DEBUG: Parameter Value #5: "105280"
DEBUG: Parameter Value #6: "\COM"
DEBUG: Parameter Value #7: "25"
DEBUG: Parameter Value #8: "2"
DEBUG: Parameter Value #9: "NO"
DEBUG: Parameter Value #10: "704"
DEBUG: Parameter Value #11: "YES"
DEBUG: Parameter Value #12: "NO"
DEBUG: Parameter Value #13: "NO"
DEBUG: Parameter Value #14: "NO"
DEBUG: Parameter Value #15: "NO"

Name                      : COM_DE_Win
Size                      : 105280
Status                    : YES
LastUsed                  : Wed Oct 14 00:49:16 2015
Accessed                  : YES
ShareOptions              : 704
Location                  : \COM
UseFileCategories         : YES
TextOnly                  : NO
RequireReason             : NO
EnforceExclusivePasswords : NO
RequireContentValidation  : NO
SafeID                    : 25
LocationID                : 2

The second issue when filename has blank included:
filename = "Operating System-DE_Win_Local-testserver-testuser "
Search-Files -vault $Vault -user $User -folder $Folder -safe $SafeWin -filePattern $FileWin -fileRetrieved:$True -Verbose -Debug
DEBUG: Processing Bound Parameters
DEBUG: "vault=""Vault""" "user=""PacliScriptUser""" "folder=""Root""" "safe=""COM_DE_Win""" "filePattern=""Operating""" "System-DE_Win_Local-testserver-testuser""" "fileRetrieved=""YES"
C:\COM_Services\SUP-026\Pacli\Pacli55\PACLI.EXE : parse error, expecting `';''
At line:1 char:1
- C:\COM_Services\SUP-026\Pacli\Pacli55\PACLI.EXE FINDFILES "vault=""Vault""" "use ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (parse error, expecting `';'':String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

DEBUG: LastExitCode: -1

**Comment by sivakumarDFS** [comment]
Hi, 
I  would like to know ,can I use  this module to  add a service Account of Privilege password Management in cyber-ark , If you have any example script please share Thanks in Advance

**Comment by bzaidfeld** [comment]
Hi sivakumarDFS,

If you are referring to setting up a new managed account in a safe and applying a default password and a platform policy to it, you best option is to use the CyberArk Password Upload Utility (it itself uses PACLI). It will ensure that the password and policy have been set correctly. Doing it on your own with custom PACLI may result in future issues at times of migration to newer versions of PIM.

If you mean something else, let me know.

Cheers,
Boris

**Comment by sivakumarDFS** [comment]
See I have an requirement to automate  adding a service account in a PPM  and changing password , I would like this to be automated through scripting is this is possible with the PowerShell module .
